default: &default
  adapter: sqlite3
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 1000

test:
  <<: *default
  database: db/test.sqlite3

development:
  <<: *default
  database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nikocale
  password: nikocale
  url: <%= ENV['DATABASE_URL'] %>
  timeout: 5000
