default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nikocale
  password: nikocale
  host: localhost
  timeout: 5000

test:
  <<: *default
  database: nikocale_test

development:
  <<: *default
  database: nikocale

production:
  <<: *default
  database: nikocale
  username: nikocale
  password: nikocale
  url: <%= ENV['DATABASE_URL'] %>